version: 0.2
env:
  parameter-store:
    AWS_DEFAULT_REGION: "/ticketpro/region"
    IMAGE_REPO_NAME: "/ticketpro/ecr_repo_name"
    IMAGE_TAG: "/ticketpro/ecr_image_tag"
    AWS_ACCOUNT_ID: "account_id"
phases:
  install:
    runtime-versions:
      docker: 23
  pre_build:
    commands:
      - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG