version: 0.2
env:
  parameter-store:
    AWS_DEFAULT_REGION: "/ticketpro/region"
    IMAGE_REPO_NAME: "/ticketpro/ecr_repo_name"
    AWS_ACCOUNT_ID: "account_id"
phases:
  install:
    runtime-versions:
      docker: 23
  pre_build:
    commands:
      - echo Logging in to Amazon ECR in region $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$(echo $AWS_ACCOUNT_ID).dkr.ecr.$(echo $AWS_DEFAULT_REGION).amazonaws.com/$(echo $IMAGE_REPO_NAME)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Using image $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI:latest --file ./TicketPro/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG