// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketPro.Data;

#nullable disable

namespace TicketPro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240125011441_Seed_Data")]
    partial class Seed_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "104B3E6E-74E7-4CD5-B3BD-2D5567AE4101",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "A83849D4-4393-4930-9C1A-319AA1572F59",
                            Name = "Executive",
                            NormalizedName = "EXECUTIVE"
                        },
                        new
                        {
                            Id = "3D8EEDC8-9B0C-4921-9681-4A55D35BD5DD",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "F9D9FA29-3F33-4C3C-9CA2-A51B11581DB7",
                            Name = "Technician",
                            NormalizedName = "TECHNICIAN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ecb59549-4167-4315-a89f-2bf998b1c289",
                            RoleId = "A83849D4-4393-4930-9C1A-319AA1572F59"
                        },
                        new
                        {
                            UserId = "3aca033f-f48d-4a76-ba7c-ac58c629a7ec",
                            RoleId = "3D8EEDC8-9B0C-4921-9681-4A55D35BD5DD"
                        },
                        new
                        {
                            UserId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            RoleId = "F9D9FA29-3F33-4C3C-9CA2-A51B11581DB7"
                        },
                        new
                        {
                            UserId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            RoleId = "F9D9FA29-3F33-4C3C-9CA2-A51B11581DB7"
                        },
                        new
                        {
                            UserId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            RoleId = "F9D9FA29-3F33-4C3C-9CA2-A51B11581DB7"
                        },
                        new
                        {
                            UserId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            RoleId = "F9D9FA29-3F33-4C3C-9CA2-A51B11581DB7"
                        },
                        new
                        {
                            UserId = "398d1dda-bc39-4208-b358-f888bfbb2ee9",
                            RoleId = "F9D9FA29-3F33-4C3C-9CA2-A51B11581DB7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TicketPro.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChargeableRate")
                        .HasColumnType("numeric");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ecb59549-4167-4315-a89f-2bf998b1c289",
                            AccessFailedCount = 0,
                            ChargeableRate = 0m,
                            ConcurrencyStamp = "dcb52449-7275-42ad-baea-3213d588c2be",
                            Email = "mshoreheim@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "Marty",
                            LastName = "Shoreheim",
                            LockoutEnabled = true,
                            NormalizedEmail = "MSHOREHEIM@LFRC.COM",
                            NormalizedUserName = "MSHOREHEIM@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO2wfiod2bMvxEqkDwbnFM88xtPo2gOSM0KrJ5nJJ4M38Dnx1Qk2WoXKiLPVpOF/ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "YS2QTXJ5CFFBKWKIVRJVQTDVCS6ZARIU",
                            TwoFactorEnabled = false,
                            UserName = "mshoreheim@lfrc.com"
                        },
                        new
                        {
                            Id = "3aca033f-f48d-4a76-ba7c-ac58c629a7ec",
                            AccessFailedCount = 0,
                            ChargeableRate = 0m,
                            ConcurrencyStamp = "7edac54f-7633-49b3-8c90-16d35ef60d78",
                            Email = "sjackson@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "Shari",
                            LastName = "Jackson",
                            LockoutEnabled = true,
                            NormalizedEmail = "SJACKSON@LFRC.COM",
                            NormalizedUserName = "SJACKSON@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA0BPAhDLT/LEHuJKiiaJf3BLfFUXqifp5DPoT5RdDZRMRg9mbTSKxqX3sSJkPjqcA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "EJGQIJIGPYKWNJSP2LHJZH47HK4NGRPJ",
                            TwoFactorEnabled = false,
                            UserName = "sjackson@lfrc.com"
                        },
                        new
                        {
                            Id = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            AccessFailedCount = 0,
                            ChargeableRate = 250.00m,
                            ConcurrencyStamp = "b1620237-28ff-4aef-b536-acb35ee49e4f",
                            Email = "cdurbin@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "Carrie",
                            LastName = "Durbin",
                            LockoutEnabled = true,
                            NormalizedEmail = "CDURBIN@LFRC.COM",
                            NormalizedUserName = "CDURBIN@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC8zLHn4ZizET8ultmwR/nf14f4csdC0hr1NWDuwm9nHzamGBnZ1tlBd1LCtkmPaww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5UMDLZ7ACFLFMOA637F2ZYXGTLUFY6G2",
                            TwoFactorEnabled = false,
                            UserName = "cdurbin@lfrc.com"
                        },
                        new
                        {
                            Id = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            AccessFailedCount = 0,
                            ChargeableRate = 100.00m,
                            ConcurrencyStamp = "d3bf6453-5611-4846-ad5b-083dac66b928",
                            Email = "dhart@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "Devin",
                            LastName = "Hart",
                            LockoutEnabled = true,
                            NormalizedEmail = "DHART@LFRC.COM",
                            NormalizedUserName = "DHART@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECP8GDTUiYpawW2QH0jQrTb+AusonHhbxf6saK3/oCzmieXQpSy58vCmQe4sOLAgBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DXQ32QG3BZXE7V2QZC4HNL5G7FJB4EW7",
                            TwoFactorEnabled = false,
                            UserName = "dhart@lfrc.com"
                        },
                        new
                        {
                            Id = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            AccessFailedCount = 0,
                            ChargeableRate = 150.00m,
                            ConcurrencyStamp = "d3bf6453-5611-4846-ad5b-083dac66b928",
                            Email = "tcolson@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "Tara",
                            LastName = "Colson",
                            LockoutEnabled = true,
                            NormalizedEmail = "TCOLSON@LFRC.COM",
                            NormalizedUserName = "TCOLSON@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECP8GDTUiYpawW2QH0jQrTb+AusonHhbxf6saK3/oCzmieXQpSy58vCmQe4sOLAgBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DXQ32QG3BZXE7V2QZC4HNL5G7FJB4EW7",
                            TwoFactorEnabled = false,
                            UserName = "tcolson@lfrc.com"
                        },
                        new
                        {
                            Id = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            AccessFailedCount = 0,
                            ChargeableRate = 140.00m,
                            ConcurrencyStamp = "d3bf6453-5611-4846-ad5b-083dac66b928",
                            Email = "jmarshall@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastName = "Marshall",
                            LockoutEnabled = true,
                            NormalizedEmail = "JMARSHALL@LFRC.COM",
                            NormalizedUserName = "JMARSHALL@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECP8GDTUiYpawW2QH0jQrTb+AusonHhbxf6saK3/oCzmieXQpSy58vCmQe4sOLAgBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DXQ32QG3BZXE7V2QZC4HNL5G7FJB4EW7",
                            TwoFactorEnabled = false,
                            UserName = "jmarshall@lfrc.com"
                        },
                        new
                        {
                            Id = "398d1dda-bc39-4208-b358-f888bfbb2ee9",
                            AccessFailedCount = 0,
                            ChargeableRate = 180.00m,
                            ConcurrencyStamp = "d3bf6453-5611-4846-ad5b-083dac66b928",
                            Email = "hbainbridge@lfrc.com",
                            EmailConfirmed = true,
                            FirstName = "Holly",
                            LastName = "Bainbridge",
                            LockoutEnabled = true,
                            NormalizedEmail = "HBAINBRIDGE@LFRC.COM",
                            NormalizedUserName = "HBAINBRIDGE@LFRC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECP8GDTUiYpawW2QH0jQrTb+AusonHhbxf6saK3/oCzmieXQpSy58vCmQe4sOLAgBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DXQ32QG3BZXE7V2QZC4HNL5G7FJB4EW7",
                            TwoFactorEnabled = false,
                            UserName = "hbainbridge@lfrc.com"
                        });
                });

            modelBuilder.Entity("TicketPro.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sheboygan",
                            Name = "Rogers Steel",
                            State = "MI",
                            StreetAddress = "123 Wasilla Way",
                            Zip = "12345"
                        },
                        new
                        {
                            Id = 2,
                            City = "Toledo",
                            Name = "Brown Motors",
                            State = "OH",
                            StreetAddress = "1042 Grand Avenue",
                            Zip = "23456"
                        },
                        new
                        {
                            Id = 3,
                            City = "Big Spur",
                            Name = "Appliance Masters",
                            State = "IN",
                            StreetAddress = "23 Highland Ridge Road",
                            Zip = "34567"
                        });
                });

            modelBuilder.Entity("TicketPro.Data.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToId")
                        .HasColumnType("text");

                    b.Property<int>("BillableHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Closed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifierId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModifierId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 21,
                            Closed = new DateTime(2023, 1, 23, 17, 0, 41, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2022, 8, 5, 20, 7, 45, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 23, 17, 0, 41, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 3,
                            Title = "Incident 5"
                        },
                        new
                        {
                            Id = 6,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 29,
                            Created = new DateTime(2021, 11, 6, 23, 30, 9, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 8, 1, 23, 19, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 1,
                            Title = "Incident 6"
                        },
                        new
                        {
                            Id = 7,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 15,
                            Closed = new DateTime(2023, 1, 18, 23, 46, 1, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2022, 9, 12, 3, 43, 46, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 9, 12, 3, 43, 46, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 3,
                            Title = "Incident 7"
                        },
                        new
                        {
                            Id = 8,
                            BillableHours = 30,
                            Created = new DateTime(2019, 4, 7, 13, 44, 10, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2019, 4, 7, 13, 44, 10, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 0,
                            Title = "Incident 8"
                        },
                        new
                        {
                            Id = 9,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 20,
                            Created = new DateTime(2020, 1, 18, 7, 24, 33, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 11, 19, 9, 4, 13, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 2,
                            Title = "Incident 9"
                        },
                        new
                        {
                            Id = 10,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 29,
                            Closed = new DateTime(2022, 9, 25, 20, 58, 32, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 6, 16, 17, 54, 37, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 9, 25, 20, 58, 32, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 3,
                            Title = "Incident 10"
                        },
                        new
                        {
                            Id = 11,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 26,
                            Created = new DateTime(2021, 9, 26, 14, 17, 24, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 3, 29, 21, 11, 25, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 1,
                            Title = "Incident 11"
                        },
                        new
                        {
                            Id = 12,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 7,
                            Created = new DateTime(2018, 10, 21, 10, 47, 38, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 9, 25, 10, 5, 38, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 1,
                            Title = "Incident 12"
                        },
                        new
                        {
                            Id = 13,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 35,
                            Created = new DateTime(2019, 1, 6, 3, 23, 13, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2020, 12, 24, 17, 38, 1, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 2,
                            Title = "Incident 13"
                        },
                        new
                        {
                            Id = 14,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 39,
                            Closed = new DateTime(2022, 10, 3, 2, 13, 31, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2020, 7, 23, 0, 27, 42, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2020, 7, 23, 0, 27, 42, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 3,
                            Title = "Incident 14"
                        },
                        new
                        {
                            Id = 15,
                            BillableHours = 12,
                            Created = new DateTime(2022, 11, 17, 18, 51, 15, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 23, 4, 54, 51, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 0,
                            Title = "Incident 15"
                        },
                        new
                        {
                            Id = 16,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 16,
                            Created = new DateTime(2022, 11, 20, 21, 15, 20, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 31, 10, 47, 57, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 1,
                            Title = "Incident 16"
                        },
                        new
                        {
                            Id = 17,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 12,
                            Closed = new DateTime(2023, 1, 2, 8, 42, 39, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2022, 7, 13, 19, 38, 27, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 2, 8, 42, 39, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 3,
                            Title = "Incident 17"
                        },
                        new
                        {
                            Id = 18,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 12,
                            Closed = new DateTime(2020, 11, 6, 7, 55, 58, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2018, 10, 28, 1, 22, 52, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2018, 10, 28, 1, 22, 52, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 3,
                            Title = "Incident 18"
                        },
                        new
                        {
                            Id = 19,
                            BillableHours = 28,
                            Created = new DateTime(2021, 4, 23, 3, 39, 21, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 22, 16, 26, 27, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 0,
                            Title = "Incident 19"
                        },
                        new
                        {
                            Id = 20,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 34,
                            Closed = new DateTime(2022, 12, 2, 17, 11, 28, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2018, 2, 10, 23, 8, 40, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 2, 17, 11, 28, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 3,
                            Title = "Incident 20"
                        },
                        new
                        {
                            Id = 21,
                            BillableHours = 15,
                            Created = new DateTime(2021, 2, 27, 10, 0, 55, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 10, 29, 5, 1, 16, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 0,
                            Title = "Incident 21"
                        },
                        new
                        {
                            Id = 22,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 37,
                            Created = new DateTime(2021, 8, 1, 17, 1, 26, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 8, 1, 17, 1, 26, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 1,
                            Title = "Incident 22"
                        },
                        new
                        {
                            Id = 23,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 27,
                            Created = new DateTime(2018, 2, 10, 11, 42, 5, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 21, 20, 53, 21, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 1,
                            Title = "Incident 23"
                        },
                        new
                        {
                            Id = 24,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 32,
                            Created = new DateTime(2021, 2, 16, 14, 8, 20, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 2, 27, 23, 49, 55, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 2,
                            Title = "Incident 24"
                        },
                        new
                        {
                            Id = 25,
                            BillableHours = 36,
                            Created = new DateTime(2019, 2, 10, 4, 54, 13, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 3, 25, 18, 26, 39, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 0,
                            Title = "Incident 25"
                        },
                        new
                        {
                            Id = 26,
                            BillableHours = 39,
                            Created = new DateTime(2020, 3, 16, 7, 41, 4, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 2, 20, 0, 19, 10, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 0,
                            Title = "Incident 26"
                        },
                        new
                        {
                            Id = 27,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 26,
                            Created = new DateTime(2019, 2, 19, 21, 33, 35, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2019, 2, 19, 21, 33, 35, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 1,
                            Title = "Incident 27"
                        },
                        new
                        {
                            Id = 28,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 3,
                            Closed = new DateTime(2022, 10, 15, 3, 5, 37, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2022, 6, 23, 1, 41, 29, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 10, 15, 3, 5, 37, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 3,
                            Title = "Incident 28"
                        },
                        new
                        {
                            Id = 29,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 32,
                            Created = new DateTime(2021, 3, 1, 10, 36, 26, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 11, 24, 23, 20, 2, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 1,
                            Title = "Incident 29"
                        },
                        new
                        {
                            Id = 30,
                            BillableHours = 32,
                            Created = new DateTime(2022, 9, 20, 13, 10, 57, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 21, 2, 32, 54, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 0,
                            Title = "Incident 30"
                        },
                        new
                        {
                            Id = 31,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 19,
                            Created = new DateTime(2022, 12, 7, 11, 4, 37, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 4, 21, 14, 40, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 1,
                            Title = "Incident 31"
                        },
                        new
                        {
                            Id = 32,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 9,
                            Created = new DateTime(2018, 8, 23, 0, 43, 34, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 11, 22, 2, 37, 41, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 1,
                            Title = "Incident 32"
                        },
                        new
                        {
                            Id = 33,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 22,
                            Created = new DateTime(2021, 12, 10, 20, 6, 24, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 11, 6, 23, 43, 7, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 1,
                            Title = "Incident 33"
                        },
                        new
                        {
                            Id = 34,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 18,
                            Created = new DateTime(2022, 8, 14, 13, 16, 43, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 9, 16, 24, 32, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 2,
                            Title = "Incident 34"
                        },
                        new
                        {
                            Id = 35,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 30,
                            Created = new DateTime(2022, 11, 28, 5, 13, 19, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 11, 19, 46, 51, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 1,
                            Title = "Incident 35"
                        },
                        new
                        {
                            Id = 36,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 38,
                            Created = new DateTime(2020, 5, 11, 21, 26, 31, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 7, 4, 1, 9, 3, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 1,
                            Title = "Incident 36"
                        },
                        new
                        {
                            Id = 37,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 8,
                            Created = new DateTime(2022, 3, 20, 7, 18, 53, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 3, 20, 7, 18, 53, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 2,
                            Title = "Incident 37"
                        },
                        new
                        {
                            Id = 38,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 10,
                            Created = new DateTime(2018, 8, 28, 5, 13, 3, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2018, 8, 28, 5, 13, 3, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 2,
                            Title = "Incident 38"
                        },
                        new
                        {
                            Id = 39,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 33,
                            Closed = new DateTime(2023, 1, 5, 13, 44, 56, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 1, 6, 23, 15, 40, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2023, 1, 5, 13, 44, 56, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 3,
                            Title = "Incident 39"
                        },
                        new
                        {
                            Id = 40,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 35,
                            Created = new DateTime(2020, 1, 8, 4, 5, 17, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 11, 5, 11, 48, 16, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 2,
                            Title = "Incident 40"
                        },
                        new
                        {
                            Id = 41,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 15,
                            Created = new DateTime(2022, 9, 16, 17, 9, 19, 0, DateTimeKind.Unspecified),
                            CreatorId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 11, 12, 12, 27, 30, 0, DateTimeKind.Unspecified),
                            ModifierId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            Status = 1,
                            Title = "Incident 41"
                        },
                        new
                        {
                            Id = 42,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 30,
                            Created = new DateTime(2018, 4, 22, 5, 58, 32, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 9, 23, 7, 36, 8, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 1,
                            Title = "Incident 42"
                        },
                        new
                        {
                            Id = 43,
                            AssignedToId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            BillableHours = 26,
                            Created = new DateTime(2021, 12, 16, 20, 19, 17, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 10, 25, 13, 24, 13, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 2,
                            Title = "Incident 43"
                        },
                        new
                        {
                            Id = 44,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 11,
                            Closed = new DateTime(2023, 1, 15, 7, 39, 21, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2019, 10, 9, 17, 16, 17, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2019, 10, 9, 17, 16, 17, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 3,
                            Title = "Incident 44"
                        },
                        new
                        {
                            Id = 45,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 22,
                            Closed = new DateTime(2022, 9, 12, 20, 38, 20, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2020, 3, 26, 20, 13, 30, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 9, 12, 20, 38, 20, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 3,
                            Title = "Incident 45"
                        },
                        new
                        {
                            Id = 46,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 36,
                            Created = new DateTime(2019, 12, 10, 1, 16, 58, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 3, 11, 18, 16, 27, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 1,
                            Title = "Incident 46"
                        },
                        new
                        {
                            Id = 47,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 15,
                            Created = new DateTime(2022, 6, 15, 3, 54, 12, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 25, 21, 46, 18, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 1,
                            Title = "Incident 47"
                        },
                        new
                        {
                            Id = 48,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 29,
                            Closed = new DateTime(2022, 12, 18, 5, 26, 51, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2019, 11, 30, 14, 1, 37, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 2,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 12, 18, 5, 26, 51, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 3,
                            Title = "Incident 48"
                        },
                        new
                        {
                            Id = 49,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 14,
                            Closed = new DateTime(2021, 5, 27, 12, 29, 53, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2019, 1, 13, 3, 45, 5, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 5, 27, 12, 29, 53, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 3,
                            Title = "Incident 49"
                        },
                        new
                        {
                            Id = 50,
                            BillableHours = 34,
                            Created = new DateTime(2020, 3, 15, 10, 14, 56, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 11, 24, 6, 16, 30, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 0,
                            Title = "Incident 50"
                        },
                        new
                        {
                            Id = 51,
                            AssignedToId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            BillableHours = 19,
                            Closed = new DateTime(2022, 1, 13, 10, 58, 36, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2021, 4, 5, 23, 13, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 1, 13, 10, 58, 36, 0, DateTimeKind.Unspecified),
                            ModifierId = "afcd7a50-a4f1-4a5f-831c-94b945f10371",
                            Status = 3,
                            Title = "Incident 51"
                        },
                        new
                        {
                            Id = 52,
                            AssignedToId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            BillableHours = 25,
                            Closed = new DateTime(2022, 7, 16, 23, 43, 17, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2022, 5, 24, 3, 30, 20, 0, DateTimeKind.Unspecified),
                            CreatorId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2022, 7, 16, 23, 43, 17, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 3,
                            Title = "Incident 52"
                        },
                        new
                        {
                            Id = 53,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 22,
                            Created = new DateTime(2019, 10, 19, 8, 14, 29, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2021, 2, 19, 16, 10, 46, 0, DateTimeKind.Unspecified),
                            ModifierId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            Status = 2,
                            Title = "Incident 53"
                        },
                        new
                        {
                            Id = 54,
                            AssignedToId = "c22d84fe-375b-4fcd-ae74-ff1235df78e2",
                            BillableHours = 35,
                            Created = new DateTime(2018, 1, 3, 16, 58, 55, 0, DateTimeKind.Unspecified),
                            CreatorId = "e666cea7-25b1-4e1e-b6fd-90a536f96ac8",
                            CustomerId = 1,
                            Description = "The flight represents a breakthrough in \"ionic wind\" technology, which uses a powerful electric field to generate charged nitrogen ions, which are then expelled from the back of the aircraft, generating thrust. Steven Barrett, an aeronautics professor at MIT and the lead author of the study published in the journal Nature, said the inspiration for the project came straight from the science fiction of his childhood. \"I was a big fan of Star Trek, and at that point I thought that the future looked like it should be planes that fly silently, with no moving parts – and maybe have a blue glow.\"",
                            Modified = new DateTime(2019, 3, 25, 8, 11, 35, 0, DateTimeKind.Unspecified),
                            ModifierId = "6cf1351a-f2b6-4504-8d22-25b3dd5437e8",
                            Status = 1,
                            Title = "Incident 54"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TicketPro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TicketPro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketPro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TicketPro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketPro.Data.Models.Ticket", b =>
                {
                    b.HasOne("TicketPro.Data.ApplicationUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("TicketPro.Data.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("TicketPro.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketPro.Data.ApplicationUser", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Modifier");
                });
#pragma warning restore 612, 618
        }
    }
}
